server:
  port: 9980

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&connectTimeout=2000&socketTimeout=2000&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
  application:
    name: demo

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    use-column-label: true
  mapper-locations: classpath:/mapper/*.xml